version: "3.7"

services:
  nginx:
    image: ghcr.io/darrylforbes/personal-website-api
    environment:
      - VIRTUAL_HOST=www.darrylforbes.me,darrylforbes.me
      - LETSENCRYPT_HOST=www.darrylforbes.me,darrylforbes.me
    networks:
      - nginx-network
    expose:
      - 80

networks:
  nginx-network:
    external:
      name: nginx-network
