version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=www.darrylforbes.me
      - LETSENCRYPT_HOST=www.darrylforbes.me
    networks:
      - nginx-network
    expose:
      - 80

networks:
  nginx-network:
    external:
      name: nginx-network
